kind: Deployment
apiVersion: apps/v1
metadata:
  name: lara-iptv3
  namespace: deafult
  labels:
    k8s-app: lara-iptv3  
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: lara-iptv3
  template:
    metadata:
      name: lara-iptv3
      creationTimestamp: null
      labels:
        k8s-app: lara-iptv3
    spec:
      containers:
        - name: lara-iptv3
          image: davin777/laravel-iptv
          args:
            - '--enable-insecure-login'
            - '--insecure-bind-address=0.0.0.0'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
